### ISSUE TITLE
Represent tuples as as arrays

### ISSUE THREAD

**Issue by bdahse** [flix/datalog-solver#11]
Tuples are currently represented as lists which has high memory overhead and makes attribute access slow.

**Comment by bdahse** [comment]
We could also represent them as Flix tuples. This should be even more compact than an array and possibly slightly faster because there is no bounds checking.

**Comment by magnus-madsen** [comment]
In fact, the `Tuple` type can be avoided if you split your map into something with `Map[..., MutSet[(a, b,c)], Map[..., MutSet[(a, b,c, d)]` and so forth.

**Comment by magnus-madsen** [comment]
A map for each arity.

**Comment by magnus-madsen** [comment]
I think a first approach could be this:

```
enum Tuple[v] {
  case Tuple1(v)
  case Tuple2(v, v)
  case Tuple3(v, v)
  case TupleN(Array[v])
```

I have chosen to go up to 3, but that should be determined theoretically and/or experimentally.
