### ISSUE TITLE
Introduce Datalog Type

### ISSUE THREAD

**Issue by magnus-madsen** [flix/datalog-solver#15]
I imagine something like:

```
enum Datalog[v] {
  case Datalog(facts: Array[...], rules: Array[...])
}
```

Introduce operators like:

```
def solve(d: Datalog): Datalog
def union(d1: Datalog, d2: Datalog): Datalog
def project(...)
def fold(...)
```

**Comment by bdahse** [comment]
I suppose the Datalog object returned by `solve` consists of all the facts in `d` plus all the new facts, but none of the rules? I.e. the minimal model of `d` (including "edb").

**Comment by magnus-madsen** [comment]
> 
> 
> I suppose the Datalog object returned by `solve` consists of all the facts in `d` plus all the new facts, but none of the rules? I.e. the minimal model of `d` (including "edb").

That is right
