### ISSUE TITLE
Refactor AST

### ISSUE THREAD

**Issue by magnus-madsen** [flix/datalog-solver#17]
I propose the following changes:

- [ ] Refactor `BodyAtom` to take an array of BodyTerms.
- [ ] Refactor the function in `GuardAtom` to take an array of values and to have an array of BodyTerm.
- [ ] Refactor `Constraint` to have an array of BodyPredicates.
- [ ] Refactor `HeadAtom`  to have an array of HeadTerms.
- [ ] Refactor `App` to have an array of HeadTerms.
- [ ] Refactor `SourceLocation` to use a 5-tuple and not a record.

Mostly to ease the translation from Flix to the AST.

As for the effects, I suggest to insert casts to pure whenever the computation is actually pure. In the future there might be an immutable array and then these casts could be removed.

**Comment by magnus-madsen** [comment]
I think https://github.com/flix/flix/pull/1775 is ready for testing.

**Comment by bdahse** [comment]
> 
> 
> I think [flix/flix#1775](https://github.com/flix/flix/pull/1775) is ready for testing.

Great, I'm working on refactoring the AST right now.
