### ISSUE TITLE
Pretty Printing Seems Broken

### ISSUE THREAD

**Issue by magnus-madsen** [flix/datalog-solver#21]
I cant get it to print a program like before.

**Comment by bdahse** [comment]
Did you try to print a RAM or Datalog program?

**Comment by magnus-madsen** [comment]
RAM.

**Comment by bdahse** [comment]
It seems to be due to a missing a case in ToString for RowVar.Index in RowVar.flix. Easy to fix, but the question is, why did the compiler not alert me to the non-exhaustive match?
