### ISSUE TITLE
Flix <=> Datalog

### ISSUE THREAD

**Issue by magnus-madsen** [flix/datalog-solver#25]
Magnus:
- Rename `subsetOf` -> `isSubsetOf`.
- Fix the signatures of Guard and App.

Benjamin:
- Add BodyTerm.Wild
- Wait for my changes to Guard and App.
- Compute stratification (when not provided).

**Comment by magnus-madsen** [comment]
OK. I think these are the definitions you should build on:

```
namespace Fixpoint/Ast {
    pub enum HeadTerm[v] {
        case Var(VarSym, SourceLocation)
        case Lit(v, SourceLocation)
        case App1(v -> v, VarSym, SourceLocation)
        case App2(v -> v -> v, VarSym, VarSym, SourceLocation)
        case App3(v -> v -> v -> v, VarSym, VarSym, VarSym, SourceLocation)
        case App4(v -> v -> v -> v -> v, VarSym, VarSym, VarSym, VarSym, SourceLocation)
        case App5(v -> v -> v -> v -> v -> v, VarSym, VarSym, VarSym, VarSym, VarSym, SourceLocation)
    }
}


namespace Fixpoint/Ast {
    pub enum BodyPredicate[v] {
        case BodyAtom(PredSym, Polarity, Array[BodyTerm[v]], SourceLocation)
        case Guard1(v -> Bool, VarSym, SourceLocation)
        case Guard2(v -> v -> Bool, VarSym, VarSym, SourceLocation)
        case Guard3(v -> v -> v -> Bool, VarSym, VarSym, VarSym, SourceLocation)
        case Guard4(v -> v -> v -> v -> Bool, VarSym, VarSym, VarSym, VarSym, SourceLocation)
        case Guard5(v -> v -> v -> v -> v -> Bool, VarSym, VarSym, VarSym, VarSym, VarSym, SourceLocation)
    }
}
```

**Comment by magnus-madsen** [comment]
Note that the functions are curried.

**Comment by magnus-madsen** [comment]
I just pushed a version of https://github.com/flix/flix/pull/1775 rebased onto master.

**Comment by bdahse** [comment]
It makes sense that Guards take VarSyms, but why doesn't App take HeadTerms?

Is it not allowed to apply a function to a literal (or literal and variable)? E.g. `A(x + 5) :- B(x).` Or do you rewrite that into `A((x -> x + 5)(x)) :- B(x)`? What about function composition: `A(f(g(x)) :- B(x).`

Not sure I understand your point about currying.

**Comment by magnus-madsen** [comment]
For currying, I don't think it matters to you, you just apply the function `f(x)(y)(z)`.

For the grammar, its because of lambda lifting (which is probably too complicated to explain here).

**Comment by bdahse** [comment]
> 
> 
> For currying, I don't think it matters to you, you just apply the function `f(x)(y)(z)`.
> 
> For the grammar, its because of lambda lifting (which is probably too complicated to explain here).

Alright, we can talk about it on monday, but can you show how one of my examples would be represented at the AST level?

**Comment by magnus-madsen** [comment]
```
A(f(g(x)) :- B(x)
// becomes
A((w ->f(g(w))(x)) :- B(x)
// which can then be lifted
```

**Comment by bdahse** [comment]
> 
> 
> ```
> A(f(g(x)) :- B(x)
> // becomes
> A((w -> f(g(w))(x)) :- B(x)
> // which can then be lifted
> ```

Okay I get it then.

**Comment by bdahse** [comment]
At this point it should be possible to run Flix programs without negation or lattice semantics. How is [#1775](https://github.com/flix/flix/pull/1775) coming along?

**Comment by magnus-madsen** [comment]
> 
> 
> At this point it should be possible to run Flix programs without negation or lattice semantics. How is [#1775](https://github.com/flix/flix/pull/1775) coming along?

I need to support guards and filters, but plain ol' Datalog programs should work.

Flix master has some changes to type classes that should be implemented in the solver.

Did you try to put the two together yet? You should be able to write a minimal program and solve it (though possibly not print it...)
