### ISSUE TITLE
Possible Loop

### ISSUE THREAD

**Issue by magnus-madsen** [flix/datalog-solver#33]
I cannot be 100% sure this is in the solver and not in the translation, but this programs:

```
[R(23).]
[R(23) :- R(23).]
```

seems to loop.

Can you try to debug on your side, then I debug on my side.

**Comment by magnus-madsen** [comment]
This also does not terminate:

```
def main(_: Array[String]): Int32 & Impure =
    "fs" |> println;
    let _h = solve #{C(123). C(123) :- C(123).};
    panic("Oh noes!")

```

**Comment by magnus-madsen** [comment]
Printing the program:

```
def main(_: Array[String]): Int32 & Impure =
    "fs" |> println;
    (#{C(123). C(123) :- C(123).}) as Fixpoint/Ast.Datalog[Boxed] |> println;
    panic("Oh noes!")
```

suggests that the translation is correct.

**Comment by magnus-madsen** [comment]
@bdahse Any ideas?

**Comment by bdahse** [comment]
I'll try to debug it without going through the Flix compiler, to see if it still loops. 

Apparently I don't get emails about new issues. Sorry about the late response. I have "watched" the repo now.

**Comment by bdahse** [comment]
Off the top of my head, it may have something to do with a predicate being both EDB and IDB, even though we are not supposed to have such a distinction in Flix.

**Comment by magnus-madsen** [comment]
Loop seems fixed, but now I get wrong results. Check out `Test.Predicate.Guard`.

For example:

```
    @test
    def testGuardConst01(): Bool =
        let c = R(1, 1) :- if true.;
        let r = solve c;
        r |= R(1, 1).
```

**Comment by bdahse** [comment]
> 
> 
> Loop seems fixed, but now I get wrong results. Check out `Test.Predicate.Guard`.
> 
> For example:
> 
> ```
>     @test
>     def testGuardConst01(): Bool =
>         let c = R(1, 1) :- if true.;
>         let r = solve c;
>         r |= R(1, 1).
> ```

Did this test pass before?

**Comment by magnus-madsen** [comment]
No, because some other test never terminated in that suite.

**Comment by magnus-madsen** [comment]
Or rather, I dont know :)

**Comment by bdahse** [comment]
Ugh it's because the precedence graph is empty, so an empty program is generated.

**Comment by magnus-madsen** [comment]
Fixed, right?

**Comment by bdahse** [comment]
> 
> 
> Fixed, right?

Yep.
