### ISSUE TITLE
Do not infer bottom facts

### ISSUE THREAD

**Issue by magnus-madsen** [flix/datalog-solver#34]
The program `introduction.flix` shows that sometimes the solver can infer bottom facts:

```
LocalVar(v; Bot).
LocalVar(w; Cst(10)).
LocalVar(x; Cst(3)).
LocalVar(y; Cst(7)).
LocalVar(z; Cst(0)).
```

A bottom fact should never be explicitly stored (since it is always true).

**Comment by magnus-madsen** [comment]
@bdahse Ping to make sure you see it.

**Comment by bdahse** [comment]
I'm not sure I understand why it's bad to store bottom facts. I get that it's trivially true, but what's the harm? That it's not space efficient to store them?

**Comment by magnus-madsen** [comment]
I can see several issues:

- Space inefficiency. 
- Issues related to equality and the size (i.e. number of facts in a minimal model.)
- Issues related to termination. (Sure maybe it works right now...)
- General confusion about the semantics.

Does this program behave correctly?

```
A(Bot).
R(42) :- A(x).
```

**Comment by bdahse** [comment]
> 
> 
> I can see several issues:
> 
>     * Space inefficiency.
> 
>     * Issues related to equality and the size (i.e. number of facts in a minimal model.)
> 
>     * Issues related to termination. (Sure maybe it works right now...)
> 
>     * General confusion about the semantics.
> 
> 
> Does this program behave correctly?
> 
> ```
> A(Bot).
> R(42) :- A(x).
> ```

That program has the minimal model `R(42). A(Bot)` which I would argue is correct. It has no lattice semantics so why should bottom be treated specially? What if the program looked like:
```
A(23; Bot).
R(42) :- A(x; s).
```
Should the mapping `23 -> Bot` be ignored (not stored) because it happens to be bottom?

**Comment by magnus-madsen** [comment]
> ```
> A(23; Bot).
> R(42) :- A(x; s).
> ```
> 
> Should the mapping `23 -> Bot` be ignored (not stored) because it happens to be bottom?

Yes, I would argue so.

**Comment by bdahse** [comment]
This should be fixed in https://github.com/flix/flix/pull/1851.
